# base image
FROM node:alpine

# Set the working directory to /app
WORKDIR '/app/'

COPY package.json .


# Install any needed packages specified in requirements.txt
RUN npm install

COPY . .

# Make port 80 available to the world outside this container
#EXPOSE 80

# Define environment variable
#ENV NAME World

# Run npm start  when the container launches
CMD ["npm", "run", "start"]